const lottie = require('lottie-web');


window.addEventListener('DOMContentLoaded', () => {
    makeListOfAnimations();
})

function makeListOfAnimations() {
    let items = [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Apostrophe',
        'BlinkingCursor',
        'Colon',
        'Comma',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Apostrophe',
        'BlinkingCursor',
        'Colon',
        'Comma',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Apostrophe',
        'BlinkingCursor',
        'Colon',
        'Comma',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Apostrophe',
        'BlinkingCursor',
        'Colon',
        'Comma',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Apostrophe',
        'BlinkingCursor',
        'Colon',
        'Comma',
    ];


    let lottieDiv = document.getElementById('lottie');

    items.forEach(function (item) {
        let div = document.createElement('div');
        div.style.cssText = 'width:50px; height:50px;';
        lottieDiv.appendChild(div);

        lottie.loadAnimation({
            container: div,
            path: `lottie/${item}.json`,
            renderer: 'svg',
            loop: true,
            autoplay: true,
            // rendererSettings: {
            //     scaleMode: 'scale',
            // }
        })
    });
}